### ISSUE TITLE
Documentation for client.GetSTH() references GetAndParse()

### ISSUE THREAD

**Issue by RJPercival** [google/monologue#14]
https://github.com/google/monologue/blob/b8497a1eb13f783299398148925da2107f7e30b1/client/client.go#L177-L183
The above documentation refers to "GetAndParse()", which is an unexported function (its actual name is "getAndParse()". This makes this part of the documentation unhelpful when viewed on [godoc.org](https://godoc.org/github.com/google/monologue/client), since that function doesn't appear. Please consider:
- rewording this part of the documentation
- avoiding references to unexported code in the documentation of exported code

**Comment by taknira** [comment]
http://go/gh/google/monologue/pull/18

**Comment by RJPercival** [comment]
FYI, you can get GitHub to automatically associate (and close) an issue with a PR by writing "fixes #14" in the description.

**Comment by taknira** [comment]
I assumed their was a way, but did not know what it was :)
