### ISSUE TITLE
Logging does not include severity

### ISSUE THREAD

**Issue by RJPercival** [google/monologue#22]
The standard Go log package is being used (`log`), which does not support severity levels (e.g. INFO, WARN, ERROR). It will be easier to migrate to `github.com/golang/glog` sooner rather than later, and this will provide more expressive logging. Severity levels are particularly useful for highlighting errors amongst a sea of routine log messages.

**Comment by taknira** [comment]
Yup, agreed, and there are other pertinent reasons for switching to glog too, will do this asap :)
